### ISSUE TITLE
About the config of large ConQueR.

### ISSUE THREAD

**Issue by AlmoonYsl** [poodarchu/EFG#8]
Hi, I found that there is no config of large backbone and 4x resolution about ConQueR in the repo.
Can you share the config? Thanks.

**Comment by AlmoonYsl** [comment]
I wrote a large config myself. Is it correct?
```
model:
    weights: null 

    # common variables
    hidden_dim: 256
    aux_loss: true
    loss:
        bbox_loss_coef: 4
        giou_loss_coef: 2
        class_loss_coef: 1
        rad_loss_coef: 4
        matcher:
            class_weight: ${model.loss.class_loss_coef}
            bbox_weight: ${model.loss.bbox_loss_coef}
            giou_weight: ${model.loss.giou_loss_coef}
            rad_weight: ${model.loss.rad_loss_coef}

    metrics:
        - type: accuracy
          params: {}

    sparse_resnets:
        # num_classes: 1000
        depth: 18
        out_features: [res2, res3, res4]
        num_groups: 1
        # Options: FrozenBN, GN, "SyncBN", "BN"
        norm: BN1d
        activation:
            type: ReLU
            inplace: True
        # zero_init_residual: True
        width_per_group: 128
        # stride_in_1x1: False
        # res5_dilation: 1
        res1_out_channels: 128
        stem_out_channels: 64

    fpn:
        in_features: [res2, res3, res4]
        top_block_in_feature: "p4"
        out_channels: 256
        norm: BN
        fuse_type: sum

    backbone:
        type: voxelnet 
        hidden_dim: ${model.hidden_dim}
        position_encoding: sine 
        out_features: [p2, ]
        reader:
            norm: BN
        extractor:
            resnet: ${model.sparse_resnets}
            fpn: ${model.fpn} 
        out_channels: 256
```
Looking forward to your reply!
